url: https://jpolewczyk.com
#baseurl: /resume.github.io

# Site settings
title: jp.is()
email: joanna.polewczyk@gmail.com
description: "Resume of Joanna Polewczyk"


# Team names, titles and social links
people:
- name: Kay
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/joanna-polewczyk
  - title: github
    url: https://github.com/polewczykjoanna

# Postal address (add as many lines as necessary)
address:
  - line: Do
  - line: Germany

# Build settings
markdown: kramdown
permalink: pretty